<a href="https://colab.research.google.com/github/drpetros11111/FS_DScML_Zero_to_Mastery/blob/15_Introduction_to_Numpy/introduction_to_numpy_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [200]:
import numpy as np

## 1. DataTypes & Attributes

In [201]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [202]:
type(a1)

numpy.ndarray

In [203]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [204]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [205]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [206]:
a1.shape

(3,)

In [207]:
a2.shape

(2, 3)

In [208]:
a3.shape

(2, 3, 3)

In [209]:
a1

array([1, 2, 3])

In [210]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [211]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [212]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [213]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [214]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [215]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [216]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [217]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [218]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [219]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [220]:
sample_array.dtype

dtype('int64')

In [221]:
ones = np.ones((2, 3))

In [222]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [223]:
ones.dtype

dtype('float64')

In [224]:
type(ones)

numpy.ndarray

In [225]:
zeros = np.zeros((2, 3))

In [226]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [227]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [228]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[1, 1, 5, 3, 2],
       [0, 4, 8, 7, 1],
       [4, 9, 3, 6, 7]])

In [229]:
random_array.size

15

In [230]:
random_array.shape

(3, 5)

In [231]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.63847702, 0.86288872, 0.63662654],
       [0.99929706, 0.51778008, 0.32761664],
       [0.09877324, 0.5667664 , 0.21520794],
       [0.01179079, 0.29921532, 0.03897743],
       [0.97621382, 0.55145308, 0.07171621]])

In [232]:
random_array_2.shape

(5, 3)

In [233]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.34006782, 0.24290239, 0.10735082],
       [0.77033058, 0.35060155, 0.18764274],
       [0.91265269, 0.86114826, 0.39889823],
       [0.54633644, 0.45037544, 0.69359919],
       [0.21384609, 0.3237989 , 0.73989292]])

In [234]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [235]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [236]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [237]:
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

## 3. Viewing arrays and matrices

In [238]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [239]:
a1

array([1, 2, 3])

In [240]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [241]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [242]:
a1[0]

1

In [243]:
a2.shape

(2, 3)

In [244]:
a2[0]

array([1. , 2. , 3.3])

In [245]:
a3.shape

(2, 3, 3)

In [246]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [247]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [248]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [249]:
a2[1]

array([4. , 5. , 6.5])

In [250]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [251]:
a3.shape

(2, 3, 3)

In [252]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [253]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [254]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [255]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [256]:
a1

array([1, 2, 3])

In [257]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [258]:
a1 + ones

array([2., 3., 4.])

In [259]:
a1 - ones

array([0., 1., 2.])

In [260]:
a1 * ones

array([1., 2., 3.])

In [261]:
a1

array([1, 2, 3])

In [262]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [263]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [264]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [266]:
# How can you reshape a2 to be compatible with a3?
# Search: "How to reshape numpy array"

import numpy as np  # Import NumPy for array manipulation

# Reshape a2 to be compatible with a3 for broadcasting
a2_reshaped = a2[:,:, np.newaxis]  # Add a new axis to a2

# Now you can perform the multiplication
result = a2_reshaped * a3

print(result)

[[[  1.    2.    3. ]
  [  8.   10.   12. ]
  [ 23.1  26.4  29.7]]

 [[ 40.   44.   48. ]
  [ 65.   70.   75. ]
  [104.  110.5 117. ]]]


Let's break down the expression a2[:,:, np.newaxis]:

Understanding Array Slicing and np.newaxis

Array Slicing: In NumPy, you can extract portions of an array using slicing. The general syntax is array[start:stop:step]. When you use colons without specifying start and stop indices, it selects all elements along that dimension.
np.newaxis: This is a special object in NumPy that, when used in array indexing, adds a new dimension (axis) to the array.
Putting it Together

a2[:,:]: This selects all rows and all columns of the array a2. Essentially, it's a way to reference the entire a2 array without modifying it.

np.newaxis: By placing np.newaxis as the third index (a2[:,:,np.newaxis]), you're instructing NumPy to insert a new axis along the third dimension (depth).

Effect on Shape

Let's say a2 originally has the shape (2, 3) (2 rows, 3 columns). After using a2[:,:, np.newaxis], the shape becomes (2, 3, 1) (2 rows, 3 columns, 1 depth). This effectively transforms the 2D array into a 3D array with a single element along the depth dimension.

Why This Matters for Broadcasting

Broadcasting in NumPy allows arithmetic operations between arrays with different shapes under certain conditions. One of those conditions is that dimensions must either be equal or one of them must be 1. By adding a new axis to a2 and making its depth 1, you enable broadcasting with a3, which has a depth of 3.

Let me know if you have any further questions or would like more clarification!

In [ ]:
a1 / ones

In [ ]:
a2 / a1

In [ ]:
# Floor division removes the decimals (rounds down)
a2 // a1

In [ ]:
a2

In [ ]:
a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
a1 + ones

In [ ]:
np.add(a1, ones)

In [ ]:
a1 % 2

In [ ]:
a1 / 2

In [ ]:
a2 % 2

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

### Aggregation

Aggregation = performing the same operation on a number of things

In [ ]:
listy_list = [1, 2, 3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrays (`np.sum()`).

In [ ]:
# Creative a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
massive_array[:10]

In [ ]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

In [ ]:
17900 / 34

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

**Standard deviation** and **variance** are measures of 'spread' of data.

The higher standard deviation and the higher variance of data, the more spread out the values are.

The lower standard deviation and lower variance, the less spread out the values are.

In [ ]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

In [ ]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

In [ ]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

In [ ]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

### Reshaping & transposing

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2 * a3

In [ ]:
a2.shape

In [ ]:
a2.reshape(2, 3, 1).shape

In [ ]:
a3.shape

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

In [ ]:
a2_reshape * a3

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
# Transpose = switches the axis'
a2.T

In [ ]:
a2.T.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a3.T

In [ ]:
a3.T.shape

## Dot product

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

mat1

In [ ]:
mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
mat1

In [ ]:
mat2

In [ ]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

In [ ]:
# Dot product
np.dot(mat1, mat2)

In [ ]:
# Transpose mat1
mat1.T

In [ ]:
mat1.shape, mat2.T.shape

In [ ]:
mat3 = np.dot(mat1, mat2.T)
mat3

In [ ]:
mat3.shape

### Dot product exmaple (nut butter sales)

In [ ]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

In [ ]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

In [ ]:
# Create prices array
prices = np.array([10, 8, 12])
prices

In [ ]:
prices.shape

In [199]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=["Price"],
                             columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

NameError: name 'prices' is not defined

In [ ]:
prices.shape

In [ ]:
sales_amounts.shape

In [ ]:
total_sales = prices.dot(sales_amounts)

In [ ]:
# Shape aren't aligned, let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

In [ ]:
# Create daily_sales
butter_prices.shape, weekly_sales.shape

In [ ]:
weekly_sales.T.shape

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales.shape

In [ ]:
weekly_sales.shape

In [ ]:
weekly_sales

In [131]:
# Doesn't work, not the right shape
weekly_sales["Total ($)"] = daily_sales
weekly_sales

NameError: name 'daily_sales' is not defined

In [ ]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

### Comparison Operators

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [ ]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [ ]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [ ]:
a1 > 5

array([False, False, False])

In [ ]:
a1 < 5

array([ True,  True,  True])

In [ ]:
a1 == a1

array([ True,  True,  True])

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

## 5. Sorting arrays

In [ ]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [ ]:
random_array.shape

(3, 5)

In [ ]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [ ]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [ ]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])

In [ ]:
a1

array([1, 2, 3])

In [ ]:
np.argsort(a1)

array([0, 1, 2])

In [ ]:
np.argmin(a1)

0

In [ ]:
np.argmax(a1)

2

In [ ]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [ ]:
np.argmax(random_array, axis=0)

array([1, 1, 1, 0, 0])

In [ ]:
np.argmax(random_array, axis=1)

array([4, 1, 1])

## 6. Practical Example - NumPy in Action!!!!

<img src="https://github.com/drpetros11111/FS_DScML_Zero_to_Mastery/blob/15_Introduction_to_Numpy/images/panda.png?raw=1"/>

In [ ]:
# Turn an image into a NumPy array
from matplotlib.image import imread

panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [ ]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [ ]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="https://github.com/drpetros11111/FS_DScML_Zero_to_Mastery/blob/15_Introduction_to_Numpy/images/car-photo.png?raw=1"/>

In [ ]:
car = imread("images/car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [ ]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

<img src="https://github.com/drpetros11111/FS_DScML_Zero_to_Mastery/blob/15_Introduction_to_Numpy/images/dog-photo.png?raw=1"/>

In [ ]:
dog = imread("images/dog-photo.png")
print(type(dog))

<class 'numpy.ndarray'>


In [ ]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274